configuration:
  payram.backend: ""
  payram.frontend: ""
  postal.endpoint: ""
  postal.apikey: ""
  ssl: ""
database:
  postgres.host: ""
  postgres.port: ""
  postgres.database: ""
  postgres.username: ""
  postgres.password: ""
projects:
  project1:
    name: ""
    website: ""
    successEndpoint: ""
    webhookEndpoint: ""
blockchain:
  ETH:
    client: ""
    server: ""
    server_api_key: ""
    explorer_address: ""
    explorer_transaction: ""
    min_confirmations: ""
  BTC:
    client: ""
    server: ""
    server_username: ""
    server_password: ""
  TRX:
    client: ""
    server: ""
    server_api_key: ""
wallets:
  Ethereum:
    xpub: ""
    deposit_addresses_count: ""
  Bitcoin:
    xpub: ""
    deposit_addresses_count: ""
  Trx:
    xpub: ""
    deposit_addresses_count: ""
